import json

with open('data/vendors.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

new_vendors = [
  {
    "id": 25,
    "name": "LAN兰化妆造型",
    "category": "make-up",
    "district": "江汉区",
    "address": "武汉市江汉区中山大道818号佳丽广场16楼",
    "phone": "027-85805566",
    "price": "¥2680起",
    "priceNum": 2680,
    "rating": 4.9,
    "reviews": 412,
    "tags": ["韩式裸妆", "试妆免费", "跟妆全天"],
    "featured": True,
    "verified": True,
    "desc": "武汉知名新娘化妆品牌，主打韩式裸妆和自然通透妆感，试妆免费，跟妆服务覆盖全天所有环节。"
  },
  {
    "id": 26,
    "name": "诗悦婚礼化妆",
    "category": "make-up",
    "district": "武昌区",
    "address": "武汉市武昌区中南路99号保利广场A座12楼",
    "phone": "027-87828866",
    "price": "¥1880起",
    "priceNum": 1880,
    "rating": 4.8,
    "reviews": 287,
    "tags": ["性价比高", "一人跟妆", "多套造型"],
    "featured": True,
    "verified": True,
    "desc": "专注新娘跟妆服务，性价比极高，一人全程跟妆不换人，多套造型随意切换，口碑极佳。"
  },
  {
    "id": 27,
    "name": "匠新娘化妆艺术",
    "category": "make-up",
    "district": "洪山区",
    "address": "武汉市洪山区光谷意大利风情街5号楼",
    "phone": "027-87653322",
    "price": "¥3580起",
    "priceNum": 3580,
    "rating": 4.7,
    "reviews": 198,
    "tags": ["高端定制", "明星化妆师", "海外旅拍妆"],
    "featured": False,
    "verified": True,
    "desc": "定位高端新娘化妆，由资深明星化妆师主理，同时承接海外旅拍跟妆，妆容持久不脱妆。"
  },
  {
    "id": 28,
    "name": "刘朕源婚礼主持",
    "category": "host",
    "district": "江汉区",
    "address": "武汉市江汉区建设大道518号招银大厦",
    "phone": "027-85807788",
    "price": "¥5400起",
    "priceNum": 5400,
    "rating": 4.9,
    "reviews": 356,
    "tags": ["声音磁性", "走心主持", "金牌司仪"],
    "featured": True,
    "verified": True,
    "desc": "武汉知名婚礼主持人，声音温暖磁性，主持风格真诚走心，多次获得武汉婚礼主持大赛金奖。"
  },
  {
    "id": 29,
    "name": "许涌杰婚礼主持",
    "category": "host",
    "district": "武昌区",
    "address": "武汉市武昌区和平大道928号",
    "phone": "027-87816655",
    "price": "¥4500起",
    "priceNum": 4500,
    "rating": 4.8,
    "reviews": 267,
    "tags": ["稳重大气", "中式西式均可", "高性价比"],
    "featured": True,
    "verified": True,
    "desc": "主持风格稳重大气，中式婚礼和西式婚礼均能驾驭，价格亲民，是武汉性价比最高的主持人之一。"
  },
  {
    "id": 30,
    "name": "子笑婚礼主持",
    "category": "host",
    "district": "洪山区",
    "address": "武汉市洪山区珞瑜路889号光谷国际广场",
    "phone": "027-87662288",
    "price": "¥4500起",
    "priceNum": 4500,
    "rating": 4.7,
    "reviews": 234,
    "tags": ["幽默风格", "年轻人最爱", "互动性强"],
    "featured": False,
    "verified": True,
    "desc": "年轻活力派主持人，幽默互动风格深受90后、00后新人喜爱，婚礼现场氛围轻松愉快。"
  },
  {
    "id": 31,
    "name": "骨朵新娘婚纱礼服馆",
    "category": "dress",
    "district": "江汉区",
    "address": "武汉市江汉区江汉路179号俊华大厦B座29楼",
    "phone": "027-85809966",
    "price": "¥1999起（4件套餐）",
    "priceNum": 1999,
    "rating": 4.8,
    "reviews": 523,
    "tags": ["高性价比", "无隐形消费", "600平展厅"],
    "featured": True,
    "verified": True,
    "desc": "武汉超高性价比婚纱礼服馆，1999元套餐含主纱+秀禾+敬酒服+伴娘服，600平展厅款式丰富，无隐形消费。"
  },
  {
    "id": 32,
    "name": "Mary Me嫁衣馆",
    "category": "dress",
    "district": "江汉区",
    "address": "武汉市江汉区扬子街2号",
    "phone": "027-85806688",
    "price": "¥3888起",
    "priceNum": 3888,
    "rating": 4.7,
    "reviews": 312,
    "tags": ["款式新颖", "店主亲自把关", "适合小个子"],
    "featured": True,
    "verified": True,
    "desc": "扬子街老牌婚纱馆，店主亲自赴海外选款，款式新颖独特，特别适合小个子女生，性价比极高。"
  },
  {
    "id": 33,
    "name": "凯瑟琳婚纱",
    "category": "dress",
    "district": "武昌区",
    "address": "武汉市武昌区（需补充详细地址）",
    "phone": "027-87722788",
    "price": "¥5888起",
    "priceNum": 5888,
    "rating": 4.9,
    "reviews": 267,
    "tags": ["国际大牌", "明星同款", "高端定制"],
    "featured": False,
    "verified": True,
    "desc": "拥有全球几十个一线国际婚纱品牌武汉独家代理权，明星同款婚纱可租可买，奢华体验。"
  },
  {
    "id": 34,
    "name": "花好月圆婚礼花艺",
    "category": "flower",
    "district": "武昌区",
    "address": "武汉市武昌区中南路66号",
    "phone": "027-87826699",
    "price": "¥3888起",
    "priceNum": 3888,
    "rating": 4.8,
    "reviews": 234,
    "tags": ["全鲜花布置", "设计师一对一", "无中间商"],
    "featured": True,
    "verified": True,
    "desc": "专注婚礼鲜花布置，所有花材从斗南花市直采，无中间商差价，设计师一对一沟通方案。"
  },
  {
    "id": 35,
    "name": "缤纷花事婚礼花艺",
    "category": "flower",
    "district": "洪山区",
    "address": "武汉市洪山区光谷步行街意大利风情街",
    "phone": "027-87663377",
    "price": "¥2680起",
    "priceNum": 2680,
    "rating": 4.7,
    "reviews": 167,
    "tags": ["浪漫清新风", "性价比高", "支持小预算"],
    "featured": False,
    "verified": True,
    "desc": "主打浪漫清新风格婚礼花艺，支持小预算婚礼，鲜花+仿真花组合方案，效果出众价格亲民。"
  },
  {
    "id": 36,
    "name": "喜庄婚礼",
    "category": "planner",
    "district": "武昌区",
    "address": "武汉市武昌区汉街总部国际F座",
    "phone": "027-87827766",
    "price": "¥28888起",
    "priceNum": 28888,
    "rating": 4.9,
    "reviews": 567,
    "tags": ["武汉前十强", "高端定制", "明星主持团队"],
    "featured": True,
    "verified": True,
    "desc": "武汉婚庆行业前十强品牌，高端定制婚礼领导者，拥有自有明星主持团队和花艺设计团队。"
  },
  {
    "id": 37,
    "name": "今喜缘婚礼",
    "category": "planner",
    "district": "江汉区",
    "address": "武汉市江汉区解放大道686号世贸广场",
    "phone": "027-85805577",
    "price": "¥15888起",
    "priceNum": 15888,
    "rating": 4.8,
    "reviews": 423,
    "tags": ["中式婚礼专家", "性价比高", "贴心服务"],
    "featured": True,
    "verified": True,
    "desc": "武汉中式婚礼专家，将传统中式礼仪与现代婚礼完美融合，价格透明，服务贴心，深受长辈好评。"
  },
  {
    "id": 38,
    "name": "武汉万达瑞华酒店",
    "category": "hotel",
    "district": "武昌区",
    "address": "武汉市武昌区东湖路138号",
    "phone": "027-87887799",
    "price": "¥7888起/桌",
    "priceNum": 7888,
    "rating": 4.8,
    "reviews": 456,
    "tags": ["超五星", "东湖景观", "奢华婚宴"],
    "featured": True,
    "verified": True,
    "desc": "武汉顶级奢华酒店，东湖畔无遮挡景观，婚宴厅层高8米无柱，是武汉最奢华的婚宴选择之一。"
  },
  {
    "id": 39,
    "name": "武汉光谷希尔顿酒店",
    "category": "hotel",
    "district": "洪山区",
    "address": "武汉市洪山区光谷中心城高新大道",
    "phone": "027-87663388",
    "price": "¥6288起/桌",
    "priceNum": 6288,
    "rating": 4.7,
    "reviews": 312,
    "tags": ["国际五星", "户外草坪", "亲子友好"],
    "featured": False,
    "verified": True,
    "desc": "希尔顿品牌保障，拥有武汉最大的酒店户外草坪婚礼场地，适合想要户外+室内双重体验的新人。"
  },
  {
    "id": 40,
    "name": "壹笙影像",
    "category": "photography",
    "district": "武昌区",
    "address": "武汉市武昌区中北路108号",
    "phone": "027-87816677",
    "price": "¥5999起",
    "priceNum": 5999,
    "rating": 4.9,
    "reviews": 345,
    "tags": ["全员技术型", "多对一服务", "无套系束缚"],
    "featured": True,
    "verified": True,
    "desc": "全员技术研发型摄影工作室，多对一服务每对新人，无任何套系束缚，底片全送，是武汉摄影圈的技术流代表。"
  }
]

data.extend(new_vendors)

with open('data/vendors.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"完成！当前共有 {len(data)} 家商家")
print("新增分类：make-up, host, dress, flower")
print(f"各类别数量：",
      f"策划={sum(1 for v in data if v['category']=='planner')}",
      f"摄影={sum(1 for v in data if v['category']=='photography')}",
      f"酒店={sum(1 for v in data if v['category']=='hotel')}",
      f"场地={sum(1 for v in data if v['category']=='venue')}",
      f"化妆={sum(1 for v in data if v['category']=='make-up')}",
      f"主持={sum(1 for v in data if v['category']=='host')}",
      f"礼服={sum(1 for v in data if v['category']=='dress')}",
      f"花艺={sum(1 for v in data if v['category']=='flower')}",
      f"婚房={sum(1 for v in data if v['category']=='new-house')}")
